package org.usfirst.frc3932;

public enum Commands {
	AUTO_LOW_BAR,
	AUTO_MOAT,
	AUTO_RAMPART,
	AUTO_ROUGHTERRAIN,
	AUTO_ROCKWALL,
	DRIVE_FROM_POSITION_1,
	DRIVE_FROM_POSITION_2,
	DRIVE_FROM_POSITION_3,
	DRIVE_FROM_POSITION_4,
	DRIVE_FROM_POSITION_5, 
	DO_NOTHING
}
