// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3932.subsystems;

import org.usfirst.frc3932.RobotMap;
import org.usfirst.frc3932.commands.*;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Camera extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DoubleSolenoid cameraSolenoid = RobotMap.cameraCameraSolenoid;
    private final Solenoid cameraLight = RobotMap.cameraCameraLight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public double turnByAngle = 0;
    public double driveDistance = 0;


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void TiltUp(){
   	   cameraSolenoid.set(DoubleSolenoid.Value.kForward); 	
    }
   public void TiltDown(){
	   cameraSolenoid.set(DoubleSolenoid.Value.kReverse);	
    } 
   
   public boolean isDown() {
	   return DoubleSolenoid.Value.kReverse.equals(cameraSolenoid.get());
   }
   
   public void lightOn() {
	   cameraLight.set(true);
   }
   
   public void lightOff() {
	   cameraLight.set(false);
   }
   
   public void toggleLight() {
	   cameraLight.set(!cameraLight.get());
   }
}

